version: '3'
services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - auth-service
      - menu-service
      - order-service
      - user-service
      - cart-service
      - redis

  auth-service:
    build: ./auth-service
    environment:
      - MONGO_URL=mongodb://mongodb:27017/authdb
      - JWT_SECRET=supersecret
      - SMTP_EMAIL=mvamarnath63@gmail.com
      - SMTP_PASS=almq llwf jtxm jwde
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis

  menu-service:
    build: ./menu-service
    environment:
      - MONGO_URL=mongodb://mongodb:27017/menudb
      - JWT_SECRET=supersecret
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis

  order-service:
    build: ./order-service
    environment:
      - MONGO_URL=mongodb://mongodb:27017/orderdb
      - JWT_SECRET=supersecret
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis

  cart-service:
    build: ./cart-service
    environment:
      - MONGO_URL=mongodb://mongodb:27017/cartdb
      - JWT_SECRET=supersecret
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis

  user-service:
    build: ./user-service
    environment:
      - MONGO_URL=mongodb://mongodb:27017/userdb
      - JWT_SECRET=supersecret
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api-gateway

volumes:
  mongo-data:
  redis-data: